from setuptools import setup

setup(
    name='ssh-manager',
    version='0.0.1',
    packages=['venv3.lib.python3.7.site-packages.lxml', 'venv3.lib.python3.7.site-packages.lxml.html',
              'venv3.lib.python3.7.site-packages.lxml.includes', 'venv3.lib.python3.7.site-packages.lxml.isoschematron',
              'venv3.lib.python3.7.site-packages.wcwidth', 'venv3.lib.python3.7.site-packages.wcwidth.tests',
              'venv3.lib.python3.7.site-packages.fuzzyfinder', 'venv3.lib.python3.7.site-packages.prompt_toolkit',
              'venv3.lib.python3.7.site-packages.prompt_toolkit.input',
              'venv3.lib.python3.7.site-packages.prompt_toolkit.layout',
              'venv3.lib.python3.7.site-packages.prompt_toolkit.lexers',
              'venv3.lib.python3.7.site-packages.prompt_toolkit.output',
              'venv3.lib.python3.7.site-packages.prompt_toolkit.styles',
              'venv3.lib.python3.7.site-packages.prompt_toolkit.contrib',
              'venv3.lib.python3.7.site-packages.prompt_toolkit.contrib.telnet',
              'venv3.lib.python3.7.site-packages.prompt_toolkit.contrib.completers',
              'venv3.lib.python3.7.site-packages.prompt_toolkit.contrib.regular_languages',
              'venv3.lib.python3.7.site-packages.prompt_toolkit.filters',
              'venv3.lib.python3.7.site-packages.prompt_toolkit.widgets',
              'venv3.lib.python3.7.site-packages.prompt_toolkit.clipboard',
              'venv3.lib.python3.7.site-packages.prompt_toolkit.eventloop',
              'venv3.lib.python3.7.site-packages.prompt_toolkit.shortcuts',
              'venv3.lib.python3.7.site-packages.prompt_toolkit.shortcuts.progress_bar',
              'venv3.lib.python3.7.site-packages.prompt_toolkit.completion',
              'venv3.lib.python3.7.site-packages.prompt_toolkit.application',
              'venv3.lib.python3.7.site-packages.prompt_toolkit.key_binding',
              'venv3.lib.python3.7.site-packages.prompt_toolkit.key_binding.bindings',
              'venv3.lib.python3.7.site-packages.prompt_toolkit.formatted_text',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.idna',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pytoml',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.certifi',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet.cli',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib._backport',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.msgpack',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.util',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib._securetransport',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.backports',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.colorama',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib._trie',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.filters',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treewalkers',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treeadapters',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treebuilders',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.lockfile',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.progress',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.requests',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.packaging',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol.caches',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.webencodings',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pkg_resources',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.req',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.vcs',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.utils',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.models',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.commands',
              'venv3.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.operations'],
    url='',
    license='',
    author='Thomas Wiersema',
    author_email='thomas@panelinzicht.nl',
    description='Easy SSH Manager with auto completion'
)
